### ISSUE TITLE
Directly calling buffer/file/project

### ISSUE THREAD

**Issue by ChauhanT** [jdtsmith/consult-jump-project#3]
Hi, 

I was wondering if it is possible to call the narrowed buffers (buffer/file/project) directly. 

Cheers!

**Comment by jdtsmith** [comment]
I do not understand what you are asking, can you restate this with more detail and provide an example?

**Comment by ChauhanT** [comment]
Hi, sorry, that was rather unclear indeed. I meant, when we call `consult-jump-project`, we can either scroll through the entire consult buffer, or we can narrow the buffer (using `consult-narrow-key`) to specific choices. I was wondering if there is a way to invoke, for instance, a pre-narrowed consult buffer. E.g., to go straight to the narrowed consult buffer which only shows the in-project files. 

I think it might just be me missing some key elisp chops and not knowing how to code this. I love the rigorous simplicity of your package which provides a single entry-point.

**Comment by jdtsmith** [comment]
Oh I see.  For this I recommend `project-switch-to-buffer` (`C-x p b`) instead, it does just what you want.

**Comment by ChauhanT** [comment]
Thank you! Would you know how to list the files in a project and listing the projects registered with project.el ? Sorry, I am not well-versed with all the commands yet.

**Comment by jdtsmith** [comment]
`C-x p C-h` will show you all the project commands under there.  The function (not command) `project-known-project-roots` tells you the project it knows. I don't think "files in a project" is tracked: I check recentf files underneath the project root.
